"""modified authtoken tables

Revision ID: a97c7167e160
Revises: 67a47f9678da
Create Date: 2025-04-18 11:50:33.674428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a97c7167e160'
down_revision: Union[str, None] = '67a47f9678da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_token', 'expires',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'password_reset_token', ['id'])
    op.create_unique_constraint(None, 'two_factor_confirmation', ['id'])
    op.alter_column('two_factor_token', 'expires',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'two_factor_token', ['id'])
    op.alter_column('verification_token', 'expires',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'verification_token', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_token', type_='unique')
    op.alter_column('verification_token', 'expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'two_factor_token', type_='unique')
    op.alter_column('two_factor_token', 'expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'two_factor_confirmation', type_='unique')
    op.drop_constraint(None, 'password_reset_token', type_='unique')
    op.alter_column('password_reset_token', 'expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
